### ISSUE TITLE
pre-train ERROR

### ISSUE THREAD

**Issue by ghost** [ShuvenduRoy/ActiveFER#2]
![image](https://github.com/ShuvenduRoy/ActiveFER/assets/117421898/c83e2f46-ca72-4db5-be61-a47015bc0c8e)
I used the FER13 dataset, but this part of the source code did not provide initialization for train_dataset. I followed the same initialization method as below, but during the pre training process, an error occurred as shown in the figure. I don't understand why this problem occurred. I hope to receive your answer. Thank you

**Comment by ShuvenduRoy** [comment]
This was caused by the fact that we saved the dataset as a .npy object for quick loading. It was optimal because of the small size of the datasets. 

I have updated the code to directly load from the dataset. Please download the datasets from official websites and organize them as directed in the readme.
